### PR TITLE
Added some new features

### PR DESCRIPTION
**Pull request by ghost**
Rewrote the sync module
Added After Effects keyframe export function & tracker API
Added ffmpeg-based motion blur feature
Added rendering of 360 degree equirectangular panoramic video
Rewrote forced chunk loading based on Optifine code

This is my first time submitting a Pull Request, and I sincerely hope that my codes will not cause you any trouble.

### CODE REVIEW

**Comment by mchorse** [comment]
Oh, my, god! The feature set sounds amazing! 😮

Let me try it out first before I'll merge it, and see if everything works fine. 👍

**Comment by ghost** [comment]
> Oh, my, god! The feature set sounds amazing! 😮
> 
> Let me try it out first before I'll merge it, and see if everything works fine. 👍

Hi McHorse, I just added a new feature for temporarily switching shaders while recording, don't forget to test it!

**Comment by mchorse** [comment]
> > Oh, my, god! The feature set sounds amazing! 😮
> > Let me try it out first before I'll merge it, and see if everything works fine. 👍
> 
> Hi McHorse, I just added a new feature for temporarily switching shaders while recording, don't forget to test it!

Omg, awesome! I'll try it out! 😱

**Comment by mchorse** [comment]
@NyaNLI could you provide an instruction on how I can test the AE tracking data? I tried to import it via File > Import, but it didn't do anything of what I expected. 😂

**Comment by ghost** [comment]
> @NyaNLI could you provide an instruction on how I can test the AE tracking data? I tried to import it via File > Import, but it didn't do anything of what I expected. 😂

You just need to copy all the text in the text file and paste it into the AE timeline, it should be noted that the Measure Film Size of the One-Node camera should be set to Vertically (I'm not quite sure what the original English text of this thing is, probably something similar), and the coordinate information of the tracking data is consistent with the coordinates in Minecraft.
Actually, I don't know how to create keyframe data that AE can import, so I had to use this rather awkward method, my bad. :(

**Comment by mchorse** [comment]
I tested other features and everything seems to work great! Astounding job! 👏 😊 

There are a couple things that can be adjusted:

1. The new buttons' labels in Shift + F4 screen get outside of button's box. I think they should be resized to the full width (`200` pixels) and arranged vertically at the bottom.
2. Export Panoramic Video and Inject Spherical Metadata lack tooltips.
3. You forgot to re-add yourself to `"authorList"`. 😉 

Other than that, everything is just FANTASTIC! If you want, I can take care of these 3 above, just let me know. 🙂

**Comment by ghost** [comment]
Sorry for taking so long to reply, I was just busy with some other things.
I just took care of the first thing you said, but I'm not quite sure what I should do for the second thing, so please help me fix it.
Thank you for letting me know I can add my name to the authorList >w<, I had previously felt that it was a rather rude thing to add my name without permission, so I removed it.

**Comment by mchorse** [comment]
> Sorry for taking so long to reply, I was just busy with some other things.

No worries! It was so fast in comparison to my replies. 😅 

> I just took care of the first thing you said, but I'm not quite sure what I should do for the second thing, so please help me fix it.

I'll take care of it. 

> Thank you for letting me know I can add my name to the authorList >w<, I had previously felt that it was a rather rude thing to add my name without permission, so I removed it.

It's nice that you considered it being rude, but you are certainly deserve it! These features are mind blowing! 🤯 

If everything else is fine, then is it fine to accept and publish this as a new update?

**Comment by ghost** [comment]
Of course! it's my pleasure. ^o^

**Comment by mchorse** [comment]
The [update was published](https://github.com/daipenger/minema/releases/tag/v3.6-ShaderSync) on the main repository. 🥳 

Thank you very much for working on these amazing features! 😊 

I'll work on a video that will showcase these features on the next week.

**Pull request merged**
