### PR TITLE
Fixed alpha blending for alpha screenshot function

### PR DESCRIPTION
**Pull request by sekwah41**
As the title suggests ;)

### CODE REVIEW

**Comment by sekwah41** [comment]
Not sure why its shown the past stuff for a load of it but oh well :P at least the file diff changes are right :D

**Comment by mchorse** [comment]
I suppose that's because I messed up big time 😓

**Comment by sekwah41** [comment]
@mchorse its more because ya got a bunch of branches with stuff going on at once. Ya shouldn't probably have someone pushing to 1.12.2 while you are working on 1.12.2_3.5

**Comment by mchorse** [comment]
Yeah, I know, it’s my fault, anyways, I’ll clos... you beat me to it 😂

**Pull request closed without merging**
